name: CI

on:
  push:
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-buildtrain-${{ github.ref }}-1
  cancel-in-progress: true



jobs:

  kibot:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: .kibot.yaml
          board: hw-openmower-worx.kicad_pcb
          verbose: 1
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: hw-openmower-worx
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: release

  tagged-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: .kibot.yaml
          board: hw-openmower-worx.kicad_pcb

      - name: 'Fix permissions on release/'
        run: sudo chmod 0777 release

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: hw-openmower-worx
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: release
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: release

      - name: Deploy release
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release
          destination_dir: release



